CREATE TABLE `MinerCore` (
  `TransNo` int(10) unsigned NOT NULL auto_increment,
  `UnixMinute` int(10) unsigned default NULL,
  `Date` timestamp NULL default NULL,
  `MinerWorker1_1` tinyint(3) unsigned default NULL,
  `MinerWorker1_2` tinyint(3) unsigned default NULL,
  `MinerWorker2_1` tinyint(3) unsigned default NULL,
  `MinerWorker2_2` tinyint(3) unsigned default NULL,
  `MinerWorker3_1` tinyint(3) unsigned default NULL,
  `MinerWorker3_2` tinyint(3) unsigned default NULL,
  `MinerWorker4_1` tinyint(3) unsigned default NULL,
  `MinerWorker4_2` tinyint(3) unsigned default NULL,
  `MinerWorker5_1` tinyint(3) unsigned default NULL,
  `MinerWorker5_2` tinyint(3) unsigned default NULL,
  `MinerWorker6_1` tinyint(3) unsigned default NULL,
  `MinerWorker6_2` tinyint(3) unsigned default NULL,
  `MinerWorker7_1` tinyint(3) unsigned default NULL,
  `MinerWorker7_2` tinyint(3) unsigned default NULL,
  `MinerWorker8_1` tinyint(3) unsigned default NULL,
  `MinerWorker8_2` tinyint(3) unsigned default NULL,
  `MinerWorker9_1` tinyint(3) unsigned default NULL,
  `MinerWorker9_2` tinyint(3) unsigned default NULL,
  `MinerWorker10_1` tinyint(4) default NULL,
  `MinerWorker10_2` tinyint(3) unsigned default NULL,
  `MinerWorker11_1` tinyint(3) unsigned default NULL,
  `MinerWorker11_2` tinyint(3) unsigned default NULL,
  `MinerWorker12_1` tinyint(3) unsigned default NULL,
  PRIMARY KEY  (`TransNo`),
  UNIQUE KEY `TransNo` (`TransNo`),
  UNIQUE KEY `UnixMinute` (`UnixMinute`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=cp1251;

CREATE TABLE `MinerLoad` (
  `TransNo` int(10) unsigned NOT NULL auto_increment,
  `UnixMinute` int(10) unsigned default NULL,
  `Date` timestamp NULL default NULL,
  `MinerWorker1_1` tinyint(3) unsigned default NULL,
  `MinerWorker1_2` tinyint(3) unsigned default NULL,
  `MinerWorker2_1` tinyint(3) unsigned default NULL,
  `MinerWorker2_2` tinyint(3) unsigned default NULL,
  `MinerWorker3_1` tinyint(3) unsigned default NULL,
  `MinerWorker3_2` tinyint(3) unsigned default NULL,
  `MinerWorker4_1` tinyint(3) unsigned default NULL,
  `MinerWorker4_2` tinyint(3) unsigned default NULL,
  `MinerWorker5_1` tinyint(3) unsigned default NULL,
  `MinerWorker5_2` tinyint(3) unsigned default NULL,
  `MinerWorker6_1` tinyint(3) unsigned default NULL,
  `MinerWorker6_2` tinyint(3) unsigned default NULL,
  `MinerWorker7_1` tinyint(3) unsigned default NULL,
  `MinerWorker7_2` tinyint(3) unsigned default NULL,
  `MinerWorker8_1` tinyint(3) unsigned default NULL,
  `MinerWorker8_2` tinyint(3) unsigned default NULL,
  `MinerWorker9_1` tinyint(3) unsigned default NULL,
  `MinerWorker9_2` tinyint(3) unsigned default NULL,
  `MinerWorker10_1` tinyint(4) default NULL,
  `MinerWorker10_2` tinyint(3) unsigned default NULL,
  `MinerWorker11_1` tinyint(3) unsigned default NULL,
  `MinerWorker11_2` tinyint(3) unsigned default NULL,
  `MinerWorker12_1` tinyint(3) unsigned default NULL,
  PRIMARY KEY  (`TransNo`),
  UNIQUE KEY `TransNo` (`TransNo`),
  UNIQUE KEY `UnixMinute` (`UnixMinute`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=cp1251;

CREATE TABLE `MinerTemp` (
  `TransNo` int(10) unsigned NOT NULL auto_increment,
  `UnixMinute` int(10) unsigned default NULL,
  `Date` timestamp NULL default NULL,
  `MinerWorker1_1` tinyint(3) unsigned default NULL,
  `MinerWorker1_2` tinyint(3) unsigned default NULL,
  `MinerWorker2_1` tinyint(3) unsigned default NULL,
  `MinerWorker2_2` tinyint(3) unsigned default NULL,
  `MinerWorker3_1` tinyint(3) unsigned default NULL,
  `MinerWorker3_2` tinyint(3) unsigned default NULL,
  `MinerWorker4_1` tinyint(3) unsigned default NULL,
  `MinerWorker4_2` tinyint(3) unsigned default NULL,
  `MinerWorker5_1` tinyint(3) unsigned default NULL,
  `MinerWorker5_2` tinyint(3) unsigned default NULL,
  `MinerWorker6_1` tinyint(3) unsigned default NULL,
  `MinerWorker6_2` tinyint(3) unsigned default NULL,
  `MinerWorker7_1` tinyint(3) unsigned default NULL,
  `MinerWorker7_2` tinyint(3) unsigned default NULL,
  `MinerWorker8_1` tinyint(3) unsigned default NULL,
  `MinerWorker8_2` tinyint(3) unsigned default NULL,
  `MinerWorker9_1` tinyint(3) unsigned default NULL,
  `MinerWorker9_2` tinyint(3) unsigned default NULL,
  `MinerWorker10_1` tinyint(4) default NULL,
  `MinerWorker10_2` tinyint(3) unsigned default NULL,
  `MinerWorker11_1` tinyint(3) unsigned default NULL,
  `MinerWorker11_2` tinyint(3) unsigned default NULL,
  `MinerWorker12_1` tinyint(3) unsigned default NULL,
  PRIMARY KEY  (`TransNo`),
  UNIQUE KEY `TransNo` (`TransNo`),
  UNIQUE KEY `UnixMinute` (`UnixMinute`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=cp1251;

CREATE TABLE `MinerVolt` (
  `TransNo` int(10) unsigned NOT NULL auto_increment,
  `UnixMinute` int(10) unsigned default NULL,
  `Date` timestamp NULL default NULL,
  `MinerWorker1_1` tinyint(3) unsigned default NULL,
  `MinerWorker1_2` tinyint(3) unsigned default NULL,
  `MinerWorker2_1` tinyint(3) unsigned default NULL,
  `MinerWorker2_2` tinyint(3) unsigned default NULL,
  `MinerWorker3_1` tinyint(3) unsigned default NULL,
  `MinerWorker3_2` tinyint(3) unsigned default NULL,
  `MinerWorker4_1` tinyint(3) unsigned default NULL,
  `MinerWorker4_2` tinyint(3) unsigned default NULL,
  `MinerWorker5_1` tinyint(3) unsigned default NULL,
  `MinerWorker5_2` tinyint(3) unsigned default NULL,
  `MinerWorker6_1` tinyint(3) unsigned default NULL,
  `MinerWorker6_2` tinyint(3) unsigned default NULL,
  `MinerWorker7_1` tinyint(3) unsigned default NULL,
  `MinerWorker7_2` tinyint(3) unsigned default NULL,
  `MinerWorker8_1` tinyint(3) unsigned default NULL,
  `MinerWorker8_2` tinyint(3) unsigned default NULL,
  `MinerWorker9_1` tinyint(3) unsigned default NULL,
  `MinerWorker9_2` tinyint(3) unsigned default NULL,
  `MinerWorker10_1` tinyint(4) default NULL,
  `MinerWorker10_2` tinyint(3) unsigned default NULL,
  `MinerWorker11_1` tinyint(3) unsigned default NULL,
  `MinerWorker11_2` tinyint(3) unsigned default NULL,
  `MinerWorker12_1` tinyint(3) unsigned default NULL,
  PRIMARY KEY  (`TransNo`),
  UNIQUE KEY `TransNo` (`TransNo`),
  UNIQUE KEY `UnixMinute` (`UnixMinute`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=cp1251;
